mybatis:
  mapper-locations: classpath:/mybatis/mapping/*xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animal_mall?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123